name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
    
      - name: Get dependencies
        run: flutter pub get
    
      - name: Test project
        run: flutter test
    
      - name: Build release project
        run: flutter build web

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build/web
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./build

      - name: Create gh-pages branch
        run: |
          git config --global user.email "tiagorodriguessousa9@gmail.com"
          git config --global user.name "Tiago Rodrigues Sousa"
          git checkout --orphan gh-pages
          git rm -rf .
          cp -r build/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
